[RM-7505] bootstrap: support archlinux

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -26,6 +26,20 @@ if ! [ -d virtualenv ]; then
                 exit 1
             fi
             ;;
+
+        Arch)
+            for package in "$python_package" python-virtualenv; do
+            if ! pacman -Qs -- "$package" >/dev/null 2>&1; then
+                # add a space after old values
+                missing="${missing:+$missing }$package"
+            fi
+            done
+            if [ -n "$missing" ]; then
+                echo "$0: missing required packages, please install them:" 1>&2
+                echo "  pacman -Sy $missing"
+                exit 1
+            fi
+            ;;
         esac
 
         case "$(lsb_release --id --short | awk '{print $1}')" in
@@ -42,6 +56,7 @@ if ! [ -d virtualenv ]; then
             fi
             ;;
         esac
+
     fi
 
     if [ -f /etc/redhat-release ]; then
